/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import library.Book;
import library.LibraryItem;

import static org.junit.Assert.*;

import org.junit.Assert;

public class LibraryTest {
	@Test public void testGetDataFromUserWithBarCode() {
		Book book =  new Book();
		Assert.assertTrue(book.getDataFromUser("barCode"));
	}
	
	@Test public void testGetDataFromUserWithName() {
		Book book =  new Book();
		Assert.assertTrue(book.getDataFromUser("name"));
	}
	
	@Test public void testGetDataFromUserWithAuthor() {
		Book book =  new Book();
		Assert.assertTrue(book.getDataFromUser("author"));
	}
	
	@Test public void testGetDataFromUserWithISBN() {
		Book book =  new Book();
		Assert.assertTrue(book.getDataFromUser("ISBN"));
	}
	
	@Test public void testGetDataFromUserWithNumberOFPages() {
		Book book =  new Book();
		Assert.assertTrue(book.getDataFromUser("numberOfPages"));
	}
	
	@Test public void testGetDataFromUserWithEdition() {
		Book book =  new Book();
		Assert.assertTrue(book.getDataFromUser("edition"));
	}
	
	@Test public void testGetDataFromUserWithAvailable() {
		Book book =  new Book();
		Assert.assertTrue(book.getDataFromUser("available"));
	}
	
	@Test public void testGetDataFromUserWithSubject() {
		Book book =  new Book();
		Assert.assertTrue(book.getDataFromUser("subject"));
	}
}
